service: server # Nombre del servicio

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: authentication/register
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - Set-Cookie
      - http:
          path: authentication/login
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - Set-Cookie
      - http:
          path: authentication/refresh-token
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - Set-Cookie

      - http:
          path: authentication/verify/email
          method: post
          headers:
            - Content-Type

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    host: localhost
    cors:
      origin: '*'
      headers:
        - Content-Type
        - Authorization
        - Set-Cookie
      credentials: true
